apiVersion: v1
kind: Namespace
metadata:
  name: codexray

---
apiVersion: v1
kind: Service
metadata:
  name: codexray
  namespace: codexray
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: codexray

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codexray-pvc
  namespace: codexray
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codexray
  name: codexray
  namespace: codexray
spec:
  selector:
    matchLabels:
      app: codexray
  template:
    metadata:
      labels:
        app: codexray
    spec:
      containers:
        - name: codexray
          image: ghcr.io/codexray/codexray:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: codexray-pv
      volumes:
        - name: codexray-pv
          persistentVolumeClaim:
            claimName: codexray-pvc
